import { AgendaItem } from "../types/agenda.type";

export const DEVFEST_AGENDA: AgendaItem[] = [
  {
    id: "session-1",
    time: "09:00 AM",
    endTime: "10:00 AM",
    title: "Registrations, Delegate Kit & Morning Networking",
    description: "Check in with your Commudle QR code, collect your exclusive DevFest Ranchi 2026 delegate badge & swag kit, and connect with fellow developers over morning coffee.",
    room: "Main Registration Lounge",
    track: "General",
    tags: ["Check-in", "Swag", "Networking"],
    level: "All Levels"
  },
  {
    id: "session-2",
    time: "10:00 AM",
    endTime: "10:20 AM",
    title: "Opening Ceremony & Welcome Address: State of DevFest Ranchi",
    description: "Welcome address by GDG Ranchi Community Leads, lamp lighting with guest dignitaries, and a celebration of Ranchi's growing software ecosystem.",
    speaker: "GDG Ranchi Organizing Team",
    speakerRole: "Community Organizers",
    speakerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
    room: "Auditorium Hall A",
    track: "Keynote",
    tags: ["Inaugural", "Community", "Keynote"],
    level: "All Levels"
  },
  {
    id: "session-3",
    time: "10:20 AM",
    endTime: "11:05 AM",
    title: "Keynote: Architectural Shifts in Generative AI & Autonomous Agents",
    description: "Exploring next-gen LLM capabilities with Gemini 2.0, multimodal understanding, structured function calling, and deployment on serverless architectures.",
    speaker: "Dr. Ananya Roy",
    speakerRole: "Staff AI Research Scientist & Google Developer Expert",
    speakerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop",
    room: "Auditorium Hall A",
    track: "AI & Cloud",
    tags: ["Gemini 2.0", "Agents", "Architecture"],
    level: "Intermediate"
  },
  {
    id: "session-4",
    time: "11:15 AM",
    endTime: "12:00 PM",
    title: "Deep Dive: Modern Android & Multiplatform with Jetpack Compose",
    description: "Building production-ready, highly responsive UIs across phones, foldables, and tablets using declarative Kotlin Jetpack Compose and modern architecture patterns.",
    speaker: "Rohan Verma",
    speakerRole: "Principal Mobile Architect",
    speakerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
    room: "Auditorium Hall A",
    track: "Mobile & Web",
    tags: ["Android", "Kotlin", "Jetpack Compose"],
    level: "Intermediate"
  },
  {
    id: "session-5",
    time: "12:05 PM",
    endTime: "12:50 PM",
    title: "Zero to Scale: Planet-Scale Microservices on Google Cloud Run",
    description: "Deconstructing cold starts, concurrency tuning, VPC connectors, and zero-trust IAM for scalable backend services serving millions of queries.",
    speaker: "Vikram Malhotra",
    speakerRole: "Cloud Solutions Architect & GDE Cloud",
    speakerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop",
    room: "Hall B (Cloud Track)",
    track: "AI & Cloud",
    tags: ["Google Cloud", "Cloud Run", "Serverless"],
    level: "Advanced"
  },
  {
    id: "session-6",
    time: "12:50 PM",
    endTime: "01:50 PM",
    title: "Networking Lunch & Community Project Showcase",
    description: "Enjoy a hot buffet lunch, browse community project kiosks, meet hiring partners, and discuss tech ideas with fellow developers.",
    room: "Dining Courtyard & Exhibition Area",
    track: "General",
    tags: ["Lunch", "Demos", "Networking"],
    level: "All Levels"
  },
  {
    id: "session-7",
    time: "01:50 PM",
    endTime: "02:35 PM",
    title: "Panel: Breaking Barriers in Tech - Women Techmakers Ranchi",
    description: "An inspiring fireside discussion on leadership in technology, thriving in open source, and building inclusive engineering teams across Eastern India.",
    speaker: "Priya Murmu & Guest Leaders",
    speakerRole: "WTM Ambassadors & Senior Engineers",
    speakerAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=400&auto=format&fit=crop",
    room: "Auditorium Hall A",
    track: "Keynote",
    tags: ["WTM", "Diversity", "Leadership"],
    level: "All Levels"
  },
  {
    id: "session-8",
    time: "02:40 PM",
    endTime: "03:40 PM",
    title: "Hands-on Workshop: Building Fullstack GenAI Apps with Firebase Genkit",
    description: "Bring your laptop! Live coding session building a real-time multimodal application using Firebase Studio, Firestore vector search, and Gemini SDK.",
    speaker: "Aman Gupta",
    speakerRole: "Senior Full Stack Engineer & GDG Mentor",
    speakerAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400&auto=format&fit=crop",
    room: "Workshop Lab (Level 2)",
    track: "Workshop",
    tags: ["Firebase", "Genkit", "Hands-on"],
    level: "Intermediate"
  },
  {
    id: "session-9",
    time: "03:45 PM",
    endTime: "04:30 PM",
    title: "Next-Gen Web Performance: React 19, View Transitions & Sub-Second Loads",
    description: "How modern web standards are eliminating layout shifts, optimizing hydration, and delivering app-like transitions on low-bandwidth networks.",
    speaker: "Kavita Sen",
    speakerRole: "Frontend Lead & Open Source Maintainer",
    speakerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
    room: "Auditorium Hall A",
    track: "Mobile & Web",
    tags: ["React 19", "Web Vitals", "Performance"],
    level: "Intermediate"
  },
  {
    id: "session-10",
    time: "04:30 PM",
    endTime: "05:15 PM",
    title: "Swag Distribution, Community Group Photo & Closing Remarks",
    description: "Celebrate DevFest Ranchi 2026! Raffle draws for Google swags, official delegate certificates distribution, community photo, and vote of thanks.",
    speaker: "GDG Ranchi Organizing Team",
    speakerRole: "Community Organizers",
    speakerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
    room: "Auditorium Hall A",
    track: "General",
    tags: ["Swag", "Certificate", "Closing"],
    level: "All Levels"
  },
  {
    id: "session-11",
    time: "05:15 PM",
    endTime: "05:30 PM",
    title: "High Tea & Farewell Networking",
    description: "Wrap up the day with hot tea, snacks, exchange contact details, and join the GDG Ranchi WhatsApp & Discord communities for future events.",
    room: "Lounge & Lawns",
    track: "General",
    tags: ["High Tea", "Networking", "Farewell"],
    level: "All Levels"
  }
];
